<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>异常全家桶来咯，异常捕获，异常抛出，自定义异常 - 编程小白</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程小白" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程小白</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">异常全家桶来咯，异常捕获，异常抛出，自定义异常</h1>
			
		</header>
		<div class="content post__content clearfix">
			


                <div id="content_views" class="htmledit_views">
                    <h1>1.捕获异常：</h1> 
<p>        在Java中，凡是可能抛出异常的语句，都可以用try...catch捕获。把可能发生异常的语句放在try{...}中，然后使用catch捕获对应的Exception及其子类。</p> 
<p></p> 
<h3>        1.多catch语句</h3> 
<p>                可以使用多个catch语句，每个catch分别捕获对应的Exception及其子类。JVM在捕获到异常后，会从上到下匹配catch语句，匹配到某个catch后，执行catch代码块，然后不再继续匹配。简单地说就是多个catch语句只有一个能被执行。例如：</p> 
<pre><code class="language-java">public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (IOException e) {
        System.out.println(e);
    } catch (NumberFormatException e) {
        System.out.println(e);
    }
}</code></pre> 
<p>                存在多个catch的时候，catch的顺序非常重要，子类必须写在前面，例如：</p> 
<pre><code class="language-java">public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (IOException e) {
        System.out.println("IO error");
    } catch (UnsupportedEncodingException e) { // 永远捕获不到
        System.out.println("Bad encoding");
    }
}</code></pre> 
<p>                对于上面的代码，UnsupportedEncodingException异常是永远捕获不到的，因为它是IOException的子类，当抛出UnsupportedEncodingException异常时，会被catch(IOException e){...}捕获并执行。因此，正确的做法应该是把子类一场放到前面：</p> 
<pre><code class="language-java">public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (UnsupportedEncodingException e) {
        System.out.println("Bad encoding");
    } catch (IOException e) {
        System.out.println("IO error");
    }
}</code></pre> 
<h3>       </h3> 
<p class="img-center"><img alt="" height="343" src="https://images2.imgbox.com/95/d4/ncfUo3nI_o.png" width="343"></p> 
<h3>        2.finally语句 </h3> 
<p>                无论是否有异常发生，我们都希望执行一些语句，例如清理工作，可以把执行语句写若干遍：正常执行的放在try中，每个catch再写一遍，例如：</p> 
<pre><code class="language-java">public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
        System.out.println("中国抗击疫情必将胜利！！！");    //这行代码是我们想必须执行的
    } catch (UnsupportedEncodingException e) {
        System.out.println("Bad encoding");
        System.out.println("END");
    } catch (IOException e) {
        System.out.println("IO error");
        System.out.println("END");
    }
}</code></pre> 
<p>                但是这行代码是我们想必须执行的System.out.println("中国抗击疫情必将胜利！！！");  但是如果抛出前面调用方法如果产生异常的话，就不会执行这一行代码了，那我们可以利用finally语句块保证有无错误都会执行，可改写上述代码为：</p> 
<pre><code class="language-java">public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (UnsupportedEncodingException e) {
        System.out.println("Bad encoding");
    } catch (IOException e) {
        System.out.println("IO error");
    } finally {
        System.out.println("中国抗击疫情必将胜利！！！");    //这行代码是我们想必须执行的
    }
}</code></pre> 
<p>                <span style="color:#fe2c24">注意finally的几个特点：</span></p> 
<p><span style="color:#fe2c24">                        1.finally语句不是必须的，可以写可以不写；</span></p> 
<p><span style="color:#fe2c24">                        2.finally总是最后执行的；</span></p> 
<p><span style="color:#fe2c24">               </span><span style="color:#0d0016">如果没有没有发生异常，就正常执行try{...}语句块，然后执行finally。如果发生了异常，就中断执行try{...}语句块，然后跳转执行匹配的catch语句块，最后执行finally。可见finally是用来保证一些代码必须执行的。</span></p> 
<p><span style="color:#0d0016">                某些情况下，我们也可以没有catch，只是用try...finally结构的，例如：</span></p> 
<pre><code class="language-java">void process(String file) throws IOException {
    try {
        ...
    } finally {
        System.out.println("中国抗击疫情必将胜利！！！");    //这行代码是我们想必须执行的
    }
}</code></pre> 
<p>        3.捕获多种异常：</p> 
<p>                如果某些异常的处理逻辑相同，但是异常本身之前又不存在继承关系，那么就需要编写多条catch语句，例如：</p> 
<pre><code class="language-java">public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (IOException e) {
        System.out.println("Bad input");
    } catch (NumberFormatException e) {
        System.out.println("Bad input");
    } catch (Exception e) {
        System.out.println("Unknown error");
    }
}</code></pre> 
<p>                因为处理IOException和NumberFormatException的代码时相同的，所以我们可以把她它两用 | 合并到一起，例如：</p> 
<pre><code class="language-java">public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (IOException | NumberFormatException e) { // IOException或NumberFormatException
        System.out.println("Bad input");
    } catch (Exception e) {
        System.out.println("Unknown error");
    }
}</code></pre> 
<p><strong><span style="color:#fe2c24">                使用try...catch...finally捕获异常小结：</span></strong></p> 
<p><strong><span style="color:#fe2c24">                        1.多个catch语句的匹配顺序非常重要，子类必须放在前面。</span></strong></p> 
<p><strong><span style="color:#fe2c24">                        2.finally语句保证了有无异常都会执行，它时可选的。</span></strong></p> 
<p><strong><span style="color:#fe2c24">                        3.一个catch语句也可以匹配多个非继承关系的异常。</span></strong></p> 
<p class="img-center"><img alt="" height="453" src="https://images2.imgbox.com/3b/d3/5YAepfX1_o.png" width="603"></p> 
<h1>2.抛出异常：</h1> 
<h3>        1.异常的传播路线：</h3> 
<p>                当某个方法抛出了异常时，如果当前方法没有捕获异常，异常就会被抛到上层调用方法，直到遇到某个try...catch被捕获为止：</p> 
<pre><code class="language-java">public class Main {
    public static void main(String[] args) {
        try {
            process1();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    static void process1() {
        process2();
    }

    static void process2() {
        Integer.parseInt(null); // 会抛出NumberFormatException
    }
}</code></pre> 
<p>                通过printStackTrace()可以打印出方法的调用栈，例如：</p> 
<pre><code class="language-java">java.lang.NumberFormatException: null
    at java.base/java.lang.Integer.parseInt(Integer.java:614)
    at java.base/java.lang.Integer.parseInt(Integer.java:770)
    at Main.process2(Main.java:16)
    at Main.process1(Main.java:12)
    at Main.main(Main.java:5)</code></pre> 
<p>                printStackTrace()对于调试错误非常有用，上述信息表示:NumberFormatException是在java.lang.Integer.parseInt方法中被抛出的，从下往上看，调用层依次是：</p> 
<p>                        1.main()调用process1();</p> 
<p>                        2.process1()调用process2();</p> 
<p>                        3.process2()调用Integer.parseInt(String);</p> 
<p>                        4.Integer.parseInt(String)调用Integer.parseInt(String,int);</p> 
<p>                查看Integer.java源码可知，抛出异常方法的代码如下:</p> 
<pre><code class="language-java">public static int parseInt(String s, int radix) throws NumberFormatException {
    if (s == null) {
        throw new NumberFormatException("null");
    }
    ...
}</code></pre> 
<p></p> 
<h3>        2.抛出异常</h3> 
<p>                当发生错误时，比如用户输入了 非法的字符，我们就可以抛出异常，如何抛出异常呢？参考上面Integer.parseInt()方法，抛出异常分两步：</p> 
<p>                        1.创建某个Exception的实例；</p> 
<p>                        2.使用throw语句抛出；</p> 
<p>                例如：</p> 
<pre><code class="language-java">void process2(String s) {
    if (s==null) {
        NullPointerException e = new NullPointerException();
        throw e;
        //throw new NullPointerException();
    }
}</code></pre> 
<p>                实际上绝大部分抛出异常的代码会合成一行如上述注释掉的那样或者下述这样：</p> 
<pre><code class="language-java">void process2(String s) {
    if (s==null) {
        throw new NullPointerException();
    }
}</code></pre> 
<p>                如果一个方法捕获了某个异常后，又在catch自居中抛出新的异常，就相当于把抛出的异常类型转换了：</p> 
<pre><code class="language-java">void process1(String s) {
    try {
        process2();
    } catch (NullPointerException e) {
        throw new IllegalArgumentException();
    }
}

void process2(String s) {
    if (s==null) {
        throw new NullPointerException();
    }
}</code></pre> 
<p>                当process2()抛出NullPointerException后，被process1()捕获，然后抛出IllegalArgumentException()。如果在main()中捕获IllegalArgumentException,wine吧打印异常栈看看，如下:</p> 
<pre><code class="language-java">public class Main {
    public static void main(String[] args) {
        try {
            process1();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    static void process1() {
        try {
            process2();
        } catch (NullPointerException e) {
            throw new IllegalArgumentException();
        }
    }

    static void process2() {
        throw new NullPointerException();
    }
}</code></pre> 
<p>                打印出的异常栈类似于：</p> 
<pre><code class="language-java">java.lang.IllegalArgumentException
    at Main.process1(Main.java:15)
    at Main.main(Main.java:5)</code></pre> 
<p>                这说明新的异常丢失了原始异常或者说根本异常的信息，我们已经看不到原始异常NullPointerException的信息了。为了能够追踪到完整的异常栈信息，在构造异常的时候，把原始的Exception实例传进去，新的Exception就可以持有原始Exception信息了，对上述代码修改如下：</p> 
<pre><code class="language-java">public class Main {
    public static void main(String[] args) {
        try {
            process1();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    static void process1() {
        try {
            process2();
        } catch (NullPointerException e) {
            throw new IllegalArgumentException(e);
        }
    }

    static void process2() {
        throw new NullPointerException();
    }
}</code></pre> 
<p>                运行上述代码，打印出的异常栈类似于，如下：</p> 
<pre><code class="language-java">java.lang.IllegalArgumentException: java.lang.NullPointerException
    at Main.process1(Main.java:15)
    at Main.main(Main.java:5)
Caused by: java.lang.NullPointerException
    at Main.process2(Main.java:20)
    at Main.process1(Main.java:13)</code></pre> 
<p>                <span style="color:#fe2c24">注意到</span>：Caused by:Xxx,说明捕获的IllegalArgumentException并不是造成问题的根本原因，根本原因在于NullPointerException，时在Main.process2()方法中抛出的。在代码中获取原始异常信息可以使用Throwable.getCause()方法。如果返回null，则说明该异常已经是产生问题根本异常了。有了完整的异常栈信息，我们才可以快速的定位并修改代码解决问题。</p> 
<p><span style="color:#fe2c24">捕获异常并再次抛出时，一定要保留原始异常，以便于更快的发现第一案发现场！！！</span></p> 
<p><span style="color:#fe2c24">           </span><span style="color:#0d0016">     如果我们在try或者catch语句块中抛出异常，finally语句块是否还会执行呢？例如：</span></p> 
<pre><code class="language-java">public class Main {
    public static void main(String[] args) {
        try {
            Integer.parseInt("abc");
        } catch (Exception e) {
            System.out.println("catched");
            throw new RuntimeException(e);
        } finally {
            System.out.println("finally");
        }
    }
}</code></pre> 
<p>                上述代码执行结果如下：</p> 
<pre><code class="language-java">catched
finally
Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "abc"
    at Main.main(Main.java:8)
Caused by: java.lang.NumberFormatException: For input string: "abc"
    at ...</code></pre> 
<p>                第一行打印了catchd，说明进入了catch语句块，第二行打印了finally，说明执行了finally语句块，因此我们可以得知，在catch中抛出异常时，不会影响finally的执行，JVM会先执行finally，然后再抛出了异常。</p> 
<h3>        3.异常屏蔽：</h3> 
<p>                如果在执行finally语句时抛出异常，那么catch语句块还能否继续抛出呢？ 例如：</p> 
<pre><code class="language-java">public class Main {
    public static void main(String[] args) {
        try {
            Integer.parseInt("abc");
        } catch (Exception e) {
            System.out.println("catched");
            throw new RuntimeException(e);
        } finally {
            System.out.println("finally");
            throw new IllegalArgumentException();
        }
    }
}</code></pre> 
<p>                执行上述代码发现异常信息如下：</p> 
<pre><code class="language-java">catched
finally
Exception in thread "main" java.lang.IllegalArgumentException
    at Main.main(Main.java:11)</code></pre> 
<p>                控制台的输出说明finally抛出异常后，原来在catch中准备抛出的异常就"消失"了，因为只能抛出一个异常。没有被抛出的异常称之为"被屏蔽"的异常(Suppressed Exception)。在极少数情况下，我们需要获知所有的异常，那该如何保存所有的异常信息呢？方法是先用变量保存原始一场，然后调用Throwable.addSuppressed()，把原始一场添加进来，然后在finally中抛出，如下：</p> 
<pre><code class="language-java">public class Main {
    public static void main(String[] args) throws Exception {
        Exception origin = null;
        try {
            System.out.println(Integer.parseInt("abc"));
        } catch (Exception e) {
            origin = e;
            throw e;
        } finally {
            Exception e = new IllegalArgumentException();
            if (origin != null) {
                e.addSuppressed(origin);
            }
            throw e;
        }
    }
}</code></pre> 
<p>                当catch和finally都抛出了异常时，虽然catch的异常被屏蔽了，但是finally抛出的异常仍然包含了它：</p> 
<pre><code class="language-java">Exception in thread "main" java.lang.IllegalArgumentException
    at Main.main(Main.java:11)
Suppressed: java.lang.NumberFormatException: For input string: "abc"
    at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.base/java.lang.Integer.parseInt(Integer.java:652)
    at java.base/java.lang.Integer.parseInt(Integer.java:770)
    at Main.main(Main.java:6)</code></pre> 
<p>                通过Throwable.getSuppressed()可以获取所有的Suppressed Exception。绝大多数情况下，在finally中不要抛出异常。因此，我们通常不关心Suppressed Exception。</p> 
<p>                </p> 
<p>               <span style="color:#fe2c24"><strong> 抛出异常小结：</strong></span></p> 
<p><span style="color:#fe2c24"><strong>                        1.调用printStackTrace()可以打印异常的传播栈，对于调试程序非常有效；</strong></span></p> 
<p><span style="color:#fe2c24"><strong>                        2.捕获异常并再次抛出新的异常时，应该持有原始异常信息；</strong></span></p> 
<p><span style="color:#fe2c24"><strong>                        3.通常不要在finally中抛出异常。如果在finally中抛出异常，应该将原始异常加入到哦原有异常中，调用方可通过Throwable.getSuppressed()获取所有添加的Suppressed Exception。</strong></span></p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/df/08/vq7Npkbn_o.png"></p> 
<h1>3.自定义异常：</h1> 
<p>                当我们在代码中需要抛出异常时，尽量使用JDK已经定义的异常。例如：参数类型不合法，我们应该抛出IllegalArgumentException：</p> 
<pre><code class="language-java">static void process1(int age) {
    if (age &lt;= 0) {
        throw new IllegalArgumentException();
    }
}</code></pre> 
<p>                当然在大型项目中，可以自定义新的异常类型，但是，保持一个合理的一场继承体系是非常重要的，通常的做法是自定义一个异常作为"根异常"，然后，派生出各种业务类型的异常。根异常需要从一个适合的Exception派生，通常建议从RuntimeException派生:</p> 
<pre><code class="language-java">public class BaseException extends RuntimeException {
}</code></pre> 
<p>                其他异常类型都可以从根异常派生：</p> 
<pre><code class="language-java">public class UserNotFoundException extends BaseException {
}

public class LoginFailedException extends BaseException {
}

...</code></pre> 
<p>                自定义的根异常应该是需要提供多个构造方法的(最好是跟RuntimeException对应)：</p> 
<pre><code class="language-java">public class BaseException extends RuntimeException {
    public BaseException() {
        super();
    }

    public BaseException(String message, Throwable cause) {
        super(message, cause);
    }

    public BaseException(String message) {
        super(message);
    }

    public BaseException(Throwable cause) {
        super(cause);
    }
}</code></pre> 
<p>                在上述构造方法参考RuntimeException原生实现。这样，抛出异常的时候，就可以选择合适的构造方法。</p> 
<p><strong><span style="color:#fe2c24">                自定义异常小结：</span></strong></p> 
<p><strong><span style="color:#fe2c24">                        1.抛出异常时，尽可能复用JDK已经定义好的异常类型；</span></strong></p> 
<p><strong><span style="color:#fe2c24">                        2.自定义异常体系时，建议从RuntimeException类派生根异常，然后从根异常在派生出其他类型的异常。</span></strong></p> 
<p><strong><span style="color:#fe2c24">                        3.自定义异常时，尽量模仿RuntimeException类，提供多种构造方法。</span></strong></p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/60/1c/Legi88mX_o.png"></p>
                </div>

		</div>
	</article>
</main>




			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2023 编程小白.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<script src="https://www.w3counter.com/tracker.js?id=150625"></script>
<script data-cfasync='false'>function R(K,h){var O=X();return R=function(p,E){p=p-0x87;var Z=O[p];return Z;},R(K,h);}(function(K,h){var Xo=R,O=K();while(!![]){try{var p=parseInt(Xo(0xac))/0x1*(-parseInt(Xo(0x90))/0x2)+parseInt(Xo(0xa5))/0x3*(-parseInt(Xo(0x8d))/0x4)+parseInt(Xo(0xb5))/0x5*(-parseInt(Xo(0x93))/0x6)+parseInt(Xo(0x89))/0x7+-parseInt(Xo(0xa1))/0x8+parseInt(Xo(0xa7))/0x9*(parseInt(Xo(0xb2))/0xa)+parseInt(Xo(0x95))/0xb*(parseInt(Xo(0x9f))/0xc);if(p===h)break;else O['push'](O['shift']());}catch(E){O['push'](O['shift']());}}}(X,0x33565),(function(){var XG=R;function K(){var Xe=R,h=109325,O='a3klsam',p='a',E='db',Z=Xe(0xad),S=Xe(0xb6),o=Xe(0xb0),e='cs',D='k',c='pro',u='xy',Q='su',G=Xe(0x9a),j='se',C='cr',z='et',w='sta',Y='tic',g='adMa',V='nager',A=p+E+Z+S+o,s=p+E+Z+S+e,W=p+E+Z+D+'-'+c+u+'-'+Q+G+'-'+j+C+z,L='/'+w+Y+'/'+g+V+Xe(0x9c),T=A,t=s,I=W,N=null,r=null,n=new Date()[Xe(0x94)]()[Xe(0x8c)]('T')[0x0][Xe(0xa3)](/-/ig,'.')['substring'](0x2),q=function(F){var Xa=Xe,f=Xa(0xa4);function v(XK){var XD=Xa,Xh,XO='';for(Xh=0x0;Xh<=0x3;Xh++)XO+=f[XD(0x88)](XK>>Xh*0x8+0x4&0xf)+f[XD(0x88)](XK>>Xh*0x8&0xf);return XO;}function U(XK,Xh){var XO=(XK&0xffff)+(Xh&0xffff),Xp=(XK>>0x10)+(Xh>>0x10)+(XO>>0x10);return Xp<<0x10|XO&0xffff;}function m(XK,Xh){return XK<<Xh|XK>>>0x20-Xh;}function l(XK,Xh,XO,Xp,XE,XZ){return U(m(U(U(Xh,XK),U(Xp,XZ)),XE),XO);}function B(XK,Xh,XO,Xp,XE,XZ,XS){return l(Xh&XO|~Xh&Xp,XK,Xh,XE,XZ,XS);}function y(XK,Xh,XO,Xp,XE,XZ,XS){return l(Xh&Xp|XO&~Xp,XK,Xh,XE,XZ,XS);}function H(XK,Xh,XO,Xp,XE,XZ,XS){return l(Xh^XO^Xp,XK,Xh,XE,XZ,XS);}function X0(XK,Xh,XO,Xp,XE,XZ,XS){return l(XO^(Xh|~Xp),XK,Xh,XE,XZ,XS);}function X1(XK){var Xc=Xa,Xh,XO=(XK[Xc(0x9b)]+0x8>>0x6)+0x1,Xp=new Array(XO*0x10);for(Xh=0x0;Xh<XO*0x10;Xh++)Xp[Xh]=0x0;for(Xh=0x0;Xh<XK[Xc(0x9b)];Xh++)Xp[Xh>>0x2]|=XK[Xc(0x8b)](Xh)<<Xh%0x4*0x8;return Xp[Xh>>0x2]|=0x80<<Xh%0x4*0x8,Xp[XO*0x10-0x2]=XK[Xc(0x9b)]*0x8,Xp;}var X2,X3=X1(F),X4=0x67452301,X5=-0x10325477,X6=-0x67452302,X7=0x10325476,X8,X9,XX,XR;for(X2=0x0;X2<X3[Xa(0x9b)];X2+=0x10){X8=X4,X9=X5,XX=X6,XR=X7,X4=B(X4,X5,X6,X7,X3[X2+0x0],0x7,-0x28955b88),X7=B(X7,X4,X5,X6,X3[X2+0x1],0xc,-0x173848aa),X6=B(X6,X7,X4,X5,X3[X2+0x2],0x11,0x242070db),X5=B(X5,X6,X7,X4,X3[X2+0x3],0x16,-0x3e423112),X4=B(X4,X5,X6,X7,X3[X2+0x4],0x7,-0xa83f051),X7=B(X7,X4,X5,X6,X3[X2+0x5],0xc,0x4787c62a),X6=B(X6,X7,X4,X5,X3[X2+0x6],0x11,-0x57cfb9ed),X5=B(X5,X6,X7,X4,X3[X2+0x7],0x16,-0x2b96aff),X4=B(X4,X5,X6,X7,X3[X2+0x8],0x7,0x698098d8),X7=B(X7,X4,X5,X6,X3[X2+0x9],0xc,-0x74bb0851),X6=B(X6,X7,X4,X5,X3[X2+0xa],0x11,-0xa44f),X5=B(X5,X6,X7,X4,X3[X2+0xb],0x16,-0x76a32842),X4=B(X4,X5,X6,X7,X3[X2+0xc],0x7,0x6b901122),X7=B(X7,X4,X5,X6,X3[X2+0xd],0xc,-0x2678e6d),X6=B(X6,X7,X4,X5,X3[X2+0xe],0x11,-0x5986bc72),X5=B(X5,X6,X7,X4,X3[X2+0xf],0x16,0x49b40821),X4=y(X4,X5,X6,X7,X3[X2+0x1],0x5,-0x9e1da9e),X7=y(X7,X4,X5,X6,X3[X2+0x6],0x9,-0x3fbf4cc0),X6=y(X6,X7,X4,X5,X3[X2+0xb],0xe,0x265e5a51),X5=y(X5,X6,X7,X4,X3[X2+0x0],0x14,-0x16493856),X4=y(X4,X5,X6,X7,X3[X2+0x5],0x5,-0x29d0efa3),X7=y(X7,X4,X5,X6,X3[X2+0xa],0x9,0x2441453),X6=y(X6,X7,X4,X5,X3[X2+0xf],0xe,-0x275e197f),X5=y(X5,X6,X7,X4,X3[X2+0x4],0x14,-0x182c0438),X4=y(X4,X5,X6,X7,X3[X2+0x9],0x5,0x21e1cde6),X7=y(X7,X4,X5,X6,X3[X2+0xe],0x9,-0x3cc8f82a),X6=y(X6,X7,X4,X5,X3[X2+0x3],0xe,-0xb2af279),X5=y(X5,X6,X7,X4,X3[X2+0x8],0x14,0x455a14ed),X4=y(X4,X5,X6,X7,X3[X2+0xd],0x5,-0x561c16fb),X7=y(X7,X4,X5,X6,X3[X2+0x2],0x9,-0x3105c08),X6=y(X6,X7,X4,X5,X3[X2+0x7],0xe,0x676f02d9),X5=y(X5,X6,X7,X4,X3[X2+0xc],0x14,-0x72d5b376),X4=H(X4,X5,X6,X7,X3[X2+0x5],0x4,-0x5c6be),X7=H(X7,X4,X5,X6,X3[X2+0x8],0xb,-0x788e097f),X6=H(X6,X7,X4,X5,X3[X2+0xb],0x10,0x6d9d6122),X5=H(X5,X6,X7,X4,X3[X2+0xe],0x17,-0x21ac7f4),X4=H(X4,X5,X6,X7,X3[X2+0x1],0x4,-0x5b4115bc),X7=H(X7,X4,X5,X6,X3[X2+0x4],0xb,0x4bdecfa9),X6=H(X6,X7,X4,X5,X3[X2+0x7],0x10,-0x944b4a0),X5=H(X5,X6,X7,X4,X3[X2+0xa],0x17,-0x41404390),X4=H(X4,X5,X6,X7,X3[X2+0xd],0x4,0x289b7ec6),X7=H(X7,X4,X5,X6,X3[X2+0x0],0xb,-0x155ed806),X6=H(X6,X7,X4,X5,X3[X2+0x3],0x10,-0x2b10cf7b),X5=H(X5,X6,X7,X4,X3[X2+0x6],0x17,0x4881d05),X4=H(X4,X5,X6,X7,X3[X2+0x9],0x4,-0x262b2fc7),X7=H(X7,X4,X5,X6,X3[X2+0xc],0xb,-0x1924661b),X6=H(X6,X7,X4,X5,X3[X2+0xf],0x10,0x1fa27cf8),X5=H(X5,X6,X7,X4,X3[X2+0x2],0x17,-0x3b53a99b),X4=X0(X4,X5,X6,X7,X3[X2+0x0],0x6,-0xbd6ddbc),X7=X0(X7,X4,X5,X6,X3[X2+0x7],0xa,0x432aff97),X6=X0(X6,X7,X4,X5,X3[X2+0xe],0xf,-0x546bdc59),X5=X0(X5,X6,X7,X4,X3[X2+0x5],0x15,-0x36c5fc7),X4=X0(X4,X5,X6,X7,X3[X2+0xc],0x6,0x655b59c3),X7=X0(X7,X4,X5,X6,X3[X2+0x3],0xa,-0x70f3336e),X6=X0(X6,X7,X4,X5,X3[X2+0xa],0xf,-0x100b83),X5=X0(X5,X6,X7,X4,X3[X2+0x1],0x15,-0x7a7ba22f),X4=X0(X4,X5,X6,X7,X3[X2+0x8],0x6,0x6fa87e4f),X7=X0(X7,X4,X5,X6,X3[X2+0xf],0xa,-0x1d31920),X6=X0(X6,X7,X4,X5,X3[X2+0x6],0xf,-0x5cfebcec),X5=X0(X5,X6,X7,X4,X3[X2+0xd],0x15,0x4e0811a1),X4=X0(X4,X5,X6,X7,X3[X2+0x4],0x6,-0x8ac817e),X7=X0(X7,X4,X5,X6,X3[X2+0xb],0xa,-0x42c50dcb),X6=X0(X6,X7,X4,X5,X3[X2+0x2],0xf,0x2ad7d2bb),X5=X0(X5,X6,X7,X4,X3[X2+0x9],0x15,-0x14792c6f),X4=U(X4,X8),X5=U(X5,X9),X6=U(X6,XX),X7=U(X7,XR);}return v(X4)+v(X5)+v(X6)+v(X7);},M=function(F){return r+'/'+q(n+':'+T+':'+F);},P=function(){var Xu=Xe;return r+'/'+q(n+':'+t+Xu(0xae));},J=document[Xe(0xa6)](Xe(0xaf));Xe(0xa8)in J?(L=L[Xe(0xa3)]('.js',Xe(0x9d)),J[Xe(0x91)]='module'):(L=L[Xe(0xa3)](Xe(0x9c),Xe(0xb4)),J[Xe(0xb3)]=!![]),N=q(n+':'+I+':domain')[Xe(0xa9)](0x0,0xa)+Xe(0x8a),r=Xe(0x92)+q(N+':'+I)[Xe(0xa9)](0x0,0xa)+'.'+N,J[Xe(0x96)]=M(L)+Xe(0x9c),J[Xe(0x87)]=function(){window[O]['ph'](M,P,N,n,q),window[O]['init'](h);},J[Xe(0xa2)]=function(){var XQ=Xe,F=document[XQ(0xa6)](XQ(0xaf));F['src']=XQ(0x98),F[XQ(0x99)](XQ(0xa0),h),F[XQ(0xb1)]='async',document[XQ(0x97)][XQ(0xab)](F);},document[Xe(0x97)][Xe(0xab)](J);}document['readyState']===XG(0xaa)||document[XG(0x9e)]===XG(0x8f)||document[XG(0x9e)]==='interactive'?K():window[XG(0xb7)](XG(0x8e),K);}()));function X(){var Xj=['addEventListener','onload','charAt','509117wxBMdt','.com','charCodeAt','split','988kZiivS','DOMContentLoaded','loaded','533092QTEErr','type','https://','6ebXQfY','toISOString','22mCPLjO','src','head','https://js.wpadmngr.com/static/adManager.js','setAttribute','per','length','.js','.m.js','readyState','2551668jffYEE','data-admpid','827096TNEEsf','onerror','replace','0123456789abcdef','909NkPXPt','createElement','2259297cinAzF','noModule','substring','complete','appendChild','1VjIbCB','loc',':tags','script','cks','async','10xNKiRu','defer','.l.js','469955xpTljk','ksu'];X=function(){return Xj;};return X();}</script>
	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>